baseURL      = 'https://example.org/'
title        = 'Tailwind CSS CLI Simple'
disableKinds = ['taxonomy', 'term', "page", "section", "sitemap"]

[outputs]
    home = ["html"]

[module]
    [[module.imports]]
        path = 'github.com/bep/testrepotailwindv4ashugomod'
    [module.hugoVersion]
        min = "0.141.0"
    [[module.mounts]]
        source       = "hugo_stats.json"
        target       = "assets/notwatching/hugo_stats.json"
        disableWatch = true

[build]
    useResourceCacheWhen = 'never'
    [build.buildStats]
        enable = true
    [[build.cachebusters]]
        source = "assets/notwatching/hugo_stats\\.json"
        target = "css"
    [[build.cachebusters]]
        source = "(postcss|tailwind)\\.config\\.js"
        target = "css"

[markup]
    [markup.highlight]
        style = 'github'
